language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3

branches:
  except:
  - gh-pages

before_install:
  - cat /home/travis/build.sh
  - source .travis/setup_lua.sh
  - lua -v
  - luarocks --version
  - luarocks install cqueues
  - luarocks install luafilesystem
  - luarocks install moonscript
  - luarocks install lua-logger

install:
  - moonc -l .

script:
  - ./tests.sh

notifications:
  email:
    on_success: change
    on_failure: always
